// components/landing/Navbar.vue
<script setup>
const isOpen = ref(false);
const productsOpen = ref(false);

const products = [
  { title: "EHR Bridge", path: "/products#ehr-bridge", desc: "Healthcare data integration" },
  { title: "ComplianceOS", path: "/products#compliance-os", desc: "Compliance automation" },
  { title: "Call Center AI", path: "/products#call-center-ai", desc: "AI voice agents" },
  { title: "CommBridge", path: "/products#commbridge", desc: "Unified communications" },
  { title: "AutoPRD", path: "/products#autoprd", desc: "Autonomous dev pipeline" },
  { title: "Ambient Scribe", path: "/products#ai-scribe", desc: "Medical transcription" },
  { title: "Orynx Agents", path: "/products#orynx-agents", desc: "Agentic AI SDK" },
  { title: "View All", path: "/products", desc: "See all products" },
];

const menuItems = [
  { title: "Services", path: "/services" },
  { title: "Products", path: "/products", hasDropdown: true },
  { title: "Partners", path: "/partners" },
  { title: "News", path: "/news" },
];

const closeAll = () => {
  isOpen.value = false;
  productsOpen.value = false;
};
</script>

<template>
  <nav class="fixed top-0 left-0 w-full z-50 bg-white/80 backdrop-blur-2xl shadow-nav">
    <div class="max-w-7xl mx-auto px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <NuxtLink to="/" class="flex items-center gap-2" @click="closeAll">
          <img src="~/assets/img/ORY.png" alt="Orynx" class="h-9 w-auto" />
        </NuxtLink>

        <!-- Desktop Nav -->
        <div class="hidden md:flex items-center gap-1">
          <template v-for="item in menuItems" :key="item.title">
            <div v-if="item.hasDropdown" class="relative group">
              <NuxtLink
                :to="item.path"
                class="px-4 py-2 text-sm font-medium text-text-secondary hover:text-text-primary hover:bg-surface-tertiary rounded-lg transition-colors inline-flex items-center gap-1"
              >
                {{ item.title }}
                <svg class="w-3.5 h-3.5 opacity-50" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                </svg>
              </NuxtLink>
              <div class="absolute top-full left-0 pt-2 opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200">
                <div class="bg-white rounded-2xl shadow-card ring-1 ring-border p-2 w-64">
                  <NuxtLink
                    v-for="product in products"
                    :key="product.title"
                    :to="product.path"
                    class="flex flex-col px-3 py-2.5 rounded-xl hover:bg-surface-secondary transition-colors"
                  >
                    <span class="text-sm font-medium text-text-primary">{{ product.title }}</span>
                    <span class="text-xs text-text-muted">{{ product.desc }}</span>
                  </NuxtLink>
                </div>
              </div>
            </div>
            <NuxtLink
              v-else
              :to="item.path"
              class="px-4 py-2 text-sm font-medium text-text-secondary hover:text-text-primary hover:bg-surface-tertiary rounded-lg transition-colors"
            >
              {{ item.title }}
            </NuxtLink>
          </template>
          <NuxtLink
            to="/contact"
            class="ml-2 px-5 py-2 text-sm font-medium text-white bg-primary rounded-pill hover:bg-primary-hover shadow-button transition-all duration-150"
          >
            Contact Us
          </NuxtLink>
        </div>

        <!-- Mobile Menu Button -->
        <button @click="isOpen = !isOpen" class="md:hidden p-2 rounded-lg hover:bg-surface-tertiary transition-colors">
          <svg v-if="!isOpen" class="w-6 h-6 text-text-secondary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <svg v-else class="w-6 h-6 text-text-secondary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>

    <!-- Mobile Menu -->
    <div v-show="isOpen" class="md:hidden border-t border-border bg-white">
      <div class="px-4 py-3 space-y-1">
        <template v-for="item in menuItems" :key="item.title">
          <div v-if="item.hasDropdown">
            <button
              @click="productsOpen = !productsOpen"
              class="w-full flex items-center justify-between px-3 py-2.5 text-sm font-medium text-text-secondary rounded-lg hover:bg-surface-secondary"
            >
              {{ item.title }}
              <svg class="w-4 h-4 transition-transform" :class="{ 'rotate-180': productsOpen }" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
              </svg>
            </button>
            <div v-show="productsOpen" class="pl-4 space-y-1 mt-1">
              <NuxtLink
                v-for="product in products"
                :key="product.title"
                :to="product.path"
                class="block px-3 py-2 text-sm text-text-tertiary rounded-lg hover:bg-surface-secondary"
                @click="closeAll"
              >
                {{ product.title }}
              </NuxtLink>
            </div>
          </div>
          <NuxtLink
            v-else
            :to="item.path"
            class="block px-3 py-2.5 text-sm font-medium text-text-secondary rounded-lg hover:bg-surface-secondary"
            @click="closeAll"
          >
            {{ item.title }}
          </NuxtLink>
        </template>
        <NuxtLink
          to="/contact"
          class="block px-3 py-2.5 text-sm font-medium text-white bg-primary rounded-xl text-center mt-2"
          @click="closeAll"
        >
          Contact Us
        </NuxtLink>
      </div>
    </div>
  </nav>
</template>

// components/navbar/navbar.tsx
"use client"

import { useState, useEffect, useRef } from "react"
import { Menu, X, ArrowUpRight, ChevronDown } from "lucide-react"
import { cn } from "@/lib/utils"

type NavLink = {
  label: string
  href: string
  hasDropdown?: boolean
}

type ProductLink = { label: string; href: string; desc: string }

const platformLinks: ProductLink[] = [
  { label: "EHR Bridge", href: "/products/ehr-bridge", desc: "Universal healthcare integration" },
  { label: "ComplianceOS", href: "/products/compliance-os", desc: "SOC 2 / ISO 27001 / HIPAA" },
  { label: "Call Center AI", href: "/products/call-center-ai", desc: "Sub-500ms voice agents" },
  { label: "CommBridge", href: "/products/commbridge", desc: "Unified communications layer" },
  { label: "AutoPRD", href: "/products/autoprd", desc: "Autonomous dev pipeline" },
  { label: "Orynx Agents", href: "/agents", desc: "Multi-agent AI SDK" },
]

const healthcareLinks: ProductLink[] = [
  { label: "Ambient Scribe", href: "/products/ambient-scribe", desc: "Real-time clinical transcription" },
  { label: "OpenEyes Cloud", href: "/products/openeyes-cloud", desc: "Cloud-native ophthalmology EPR" },
  { label: "MedSynth", href: "/products/medsynth", desc: "Synthetic patient data" },
  { label: "DiaWound AI", href: "/products/diawound-ai", desc: "Diabetic wound triage" },
  { label: "Orynx Education", href: "/products/orynx-education", desc: "AI-powered healthcare learning" },
]


const navLinks: NavLink[] = [
  { label: "Products", href: "/products", hasDropdown: true },
  { label: "Agents SDK", href: "/agents" },
  { label: "Technology", href: "/how-it-works" },
  { label: "Solutions", href: "/solutions" },
  { label: "About", href: "/about" },
]

export function Navbar() {
  const [isScrolled, setIsScrolled] = useState(false)
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)
  const [isProductsOpen, setIsProductsOpen] = useState(false)
  const productsTimeout = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(() => {
    const onScroll = () => setIsScrolled(window.scrollY > 8)
    onScroll()
    window.addEventListener("scroll", onScroll, { passive: true })
    return () => window.removeEventListener("scroll", onScroll)
  }, [])

  // Lock body scroll when mobile menu is open
  useEffect(() => {
    document.body.style.overflow = isMobileMenuOpen ? "hidden" : ""
    return () => { document.body.style.overflow = "" }
  }, [isMobileMenuOpen])

  return (
    <>
      <header
        className={cn(
          "fixed top-0 left-0 right-0 z-50 bg-background transition-[border-color,box-shadow] duration-200",
          isScrolled
            ? "border-b border-rule"
            : "border-b border-transparent"
        )}
      >
        <div className="mx-auto max-w-[1280px] px-6 lg:px-10">
          <nav className="flex items-center h-16 lg:h-[72px]">
            {/* Wordmark */}
            <a
              href="/"
              className="flex items-baseline group flex-shrink-0 hover:opacity-80 transition-opacity"
              aria-label="Orynx — home"
            >
              <span className="font-display font-bold text-ink text-xl lg:text-[24px] tracking-[-0.02em]">
                ORYNX
              </span>
            </a>

            {/* Desktop nav */}
            <div className="hidden lg:flex items-center gap-1 ml-auto">
              {navLinks.map((link) =>
                link.hasDropdown ? (
                  <div
                    key={link.label}
                    className="relative"
                    onMouseEnter={() => {
                      if (productsTimeout.current) clearTimeout(productsTimeout.current)
                      setIsProductsOpen(true)
                    }}
                    onMouseLeave={() => {
                      productsTimeout.current = setTimeout(() => setIsProductsOpen(false), 160)
                    }}
                  >
                    <a
                      href={link.href}
                      className="inline-flex items-center gap-1 px-3 py-2 text-[15px] font-medium text-ink-soft hover:text-ink transition-colors duration-150"
                    >
                      {link.label}
                      <ChevronDown
                        className={cn(
                          "w-3.5 h-3.5 transition-transform duration-200",
                          isProductsOpen && "rotate-180"
                        )}
                      />
                    </a>
                    {isProductsOpen && (
                      <div
                        className="absolute top-full left-0 pt-2"
                        role="menu"
                      >
                        <div className="w-[640px] bg-background border border-rule rounded-md shadow-[0_8px_24px_-8px_rgba(0,27,58,0.12)] overflow-hidden">
                          <div className="grid grid-cols-2">
                            {/* Platforms column */}
                            <div className="border-r border-rule">
                              <div className="px-5 pt-4 pb-2 font-mono text-[10px] uppercase tracking-[0.18em] text-ink-muted">
                                Platforms
                              </div>
                              {platformLinks.map((product) => (
                                <a
                                  key={product.label}
                                  href={product.href}
                                  className="flex items-baseline justify-between gap-3 px-5 py-3 hover:bg-surface transition-colors duration-150"
                                  role="menuitem"
                                >
                                  <div className="min-w-0">
                                    <div className="text-[13px] font-semibold text-ink">{product.label}</div>
                                    <div className="text-[11px] text-ink-muted mt-0.5 leading-snug">{product.desc}</div>
                                  </div>
                                  <ArrowUpRight className="w-3.5 h-3.5 text-ink-muted flex-shrink-0 mt-1" />
                                </a>
                              ))}
                            </div>

                            {/* Healthcare suite column */}
                            <div>
                              <div className="px-5 pt-4 pb-2 font-mono text-[10px] uppercase tracking-[0.18em] text-ink-muted">
                                Healthcare suite
                              </div>
                              {healthcareLinks.map((product) => (
                                <a
                                  key={product.label}
                                  href={product.href}
                                  className="flex items-baseline justify-between gap-3 px-5 py-3 hover:bg-surface transition-colors duration-150"
                                  role="menuitem"
                                >
                                  <div className="min-w-0">
                                    <div className="text-[13px] font-semibold text-ink">{product.label}</div>
                                    <div className="text-[11px] text-ink-muted mt-0.5 leading-snug">{product.desc}</div>
                                  </div>
                                  <ArrowUpRight className="w-3.5 h-3.5 text-ink-muted flex-shrink-0 mt-1" />
                                </a>
                              ))}
                            </div>
                          </div>

                          <a
                            href="/products"
                            className="flex items-center justify-between px-5 py-3 bg-surface hover:bg-rule border-t border-rule transition-colors duration-150 text-[12px] font-mono uppercase tracking-[0.14em] text-ink-soft"
                            role="menuitem"
                          >
                            View all products
                            <ArrowUpRight className="w-3.5 h-3.5" />
                          </a>
                        </div>
                      </div>
                    )}
                  </div>
                ) : (
                  <a
                    key={link.label}
                    href={link.href}
                    className="px-3 py-2 text-[15px] font-medium text-ink-soft hover:text-ink transition-colors duration-150"
                  >
                    {link.label}
                  </a>
                )
              )}
            </div>

            {/* Mobile menu button */}
            <button
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
              className="lg:hidden ml-auto p-2 -mr-2 text-ink hover:bg-surface rounded transition-colors"
              aria-label="Toggle menu"
              aria-expanded={isMobileMenuOpen}
            >
              {isMobileMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
            </button>
          </nav>
        </div>
      </header>

      {/* Mobile menu */}
      {isMobileMenuOpen && (
        <div className="fixed inset-0 z-40 bg-background pt-16 lg:hidden overflow-y-auto">
          <div className="px-6 py-8 space-y-1">
            {navLinks.map((link) => (
              <div key={link.label}>
                <a
                  href={link.href}
                  onClick={() => setIsMobileMenuOpen(false)}
                  className="flex items-center justify-between py-4 border-b border-rule"
                >
                  <span className="font-display text-2xl font-semibold text-ink tracking-[-0.02em]">
                    {link.label}
                  </span>
                  <ArrowUpRight className="w-5 h-5 text-ink-muted" />
                </a>
                {link.hasDropdown && (
                  <div className="pl-2 py-2 space-y-4">
                    <div>
                      <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-ink-muted py-2">
                        Platforms
                      </div>
                      <div className="space-y-2">
                        {platformLinks.map((product) => (
                          <a
                            key={product.label}
                            href={product.href}
                            onClick={() => setIsMobileMenuOpen(false)}
                            className="block py-2"
                          >
                            <div className="text-[14px] font-semibold text-ink">{product.label}</div>
                            <div className="text-[12px] text-ink-muted mt-0.5">{product.desc}</div>
                          </a>
                        ))}
                      </div>
                    </div>
                    <div>
                      <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-ink-muted py-2">
                        Healthcare suite
                      </div>
                      <div className="space-y-2">
                        {healthcareLinks.map((product) => (
                          <a
                            key={product.label}
                            href={product.href}
                            onClick={() => setIsMobileMenuOpen(false)}
                            className="block py-2"
                          >
                            <div className="text-[14px] font-semibold text-ink">{product.label}</div>
                            <div className="text-[12px] text-ink-muted mt-0.5">{product.desc}</div>
                          </a>
                        ))}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </>
  )
}
