// components/footer/footer.tsx
"use client"

import { motion } from "framer-motion"

const footerLinks = {
  Products: [
    { label: "EHR Bridge", href: "/products#ehr-bridge" },
    { label: "ComplianceOS", href: "/products#compliance-os" },
    { label: "Call Center AI", href: "/products#call-center-ai" },
    { label: "CommBridge", href: "/products#commbridge" },
    { label: "Orynx Agents", href: "/agents" },
  ],
  Services: [
    { label: "Web Development", href: "/services#web" },
    { label: "AI & ML Solutions", href: "/services#ai-ml" },
    { label: "LLM Integration", href: "/services#llm" },
    { label: "Custom Development", href: "/services#custom" },
  ],
  Company: [
    { label: "About", href: "/about" },
    { label: "Solutions", href: "/solutions" },
    { label: "Technology", href: "/how-it-works" },
    { label: "Contact", href: "/contact" },
  ],
}

export function Footer() {
  return (
    <footer className="bg-foreground text-background pt-20 pb-8">
      <div className="container mx-auto px-6 lg:px-12">
        {/* Main footer content */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 lg:gap-12 mb-16">
          {/* Brand column */}
          <div className="col-span-2 md:col-span-1 mb-8 md:mb-0">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
            >
              <a href="/" className="flex items-baseline mb-4 group">
                <span className="font-display font-bold text-background text-2xl tracking-[-0.02em]">
                  ORYNX
                </span>
              </a>
              <p className="text-background/60 text-sm leading-relaxed max-w-xs">
                Integration platforms, AI products, and custom software engineering. Edinburgh, Scotland.
              </p>
              <div className="mt-4 space-y-1 text-sm text-background/50">
                <p>admin@orynx.ai</p>
                <p>+44 7985 309592</p>
              </div>
            </motion.div>
          </div>

          {/* Link columns */}
          {Object.entries(footerLinks).map(([category, links], index) => (
            <motion.div
              key={category}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
            >
              <h4 className="font-semibold text-sm mb-4 text-background">{category}</h4>
              <ul className="space-y-3">
                {links.map((link) => (
                  <li key={link.label}>
                    <a
                      href={link.href}
                      className="text-sm text-background/60 hover:text-teal transition-colors"
                    >
                      {link.label}
                    </a>
                  </li>
                ))}
              </ul>
            </motion.div>
          ))}
        </div>

        {/* Divider */}
        <div className="border-t border-background/10 pt-8">
          <p className="text-sm text-background/50 text-center">
            &copy; {new Date().getFullYear()} Orynx. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  )
}

// components/landing/Footer.vue
<template>
  <footer class="bg-surface-secondary border-t border-border">
    <div class="max-w-7xl mx-auto px-6 lg:px-8 py-16">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-10">
        <div class="md:col-span-1">
          <img src="~/assets/img/ORY.png" alt="Orynx" class="h-8 w-auto mb-4" />
          <p class="text-sm text-text-tertiary leading-relaxed">
            Integration platforms, AI products, and custom software engineering.
          </p>
        </div>

        <div>
          <h3 class="label mb-4">Products</h3>
          <ul class="space-y-2.5">
            <li><NuxtLink to="/products#ehr-bridge" class="text-sm text-text-tertiary hover:text-primary transition-colors">EHR Bridge</NuxtLink></li>
            <li><NuxtLink to="/products#compliance-os" class="text-sm text-text-tertiary hover:text-primary transition-colors">ComplianceOS</NuxtLink></li>
            <li><NuxtLink to="/products#call-center-ai" class="text-sm text-text-tertiary hover:text-primary transition-colors">Call Center AI</NuxtLink></li>
            <li><NuxtLink to="/products#commbridge" class="text-sm text-text-tertiary hover:text-primary transition-colors">CommBridge</NuxtLink></li>
            <li><NuxtLink to="/products#orynx-agents" class="text-sm text-text-tertiary hover:text-primary transition-colors">Orynx Agents</NuxtLink></li>
            <li><NuxtLink to="/products" class="text-sm text-text-tertiary hover:text-primary transition-colors">View All</NuxtLink></li>
          </ul>
        </div>

        <div>
          <h3 class="label mb-4">Services</h3>
          <ul class="space-y-2.5">
            <li><NuxtLink to="/services#web" class="text-sm text-text-tertiary hover:text-primary transition-colors">Web Development</NuxtLink></li>
            <li><NuxtLink to="/services#ai-ml" class="text-sm text-text-tertiary hover:text-primary transition-colors">AI & ML Solutions</NuxtLink></li>
            <li><NuxtLink to="/services#llm" class="text-sm text-text-tertiary hover:text-primary transition-colors">LLM Integration</NuxtLink></li>
            <li><NuxtLink to="/services#custom" class="text-sm text-text-tertiary hover:text-primary transition-colors">Custom Development</NuxtLink></li>
          </ul>
        </div>

        <div>
          <h3 class="label mb-4">Company</h3>
          <ul class="space-y-2.5">
            <li><NuxtLink to="/about" class="text-sm text-text-tertiary hover:text-primary transition-colors">About</NuxtLink></li>
            <li><NuxtLink to="/partners" class="text-sm text-text-tertiary hover:text-primary transition-colors">Partners</NuxtLink></li>
            <li><NuxtLink to="/news" class="text-sm text-text-tertiary hover:text-primary transition-colors">News</NuxtLink></li>
            <li><NuxtLink to="/contact" class="text-sm text-text-tertiary hover:text-primary transition-colors">Contact</NuxtLink></li>
          </ul>
        </div>
      </div>

      <div class="mt-12 pt-8 border-t border-border flex flex-col sm:flex-row justify-between items-center gap-4">
        <p class="text-xs text-text-muted">&copy; {{ new Date().getFullYear() }} Orynx. All rights reserved.</p>
        <div class="flex items-center gap-6">
          <a href="mailto:admin@orynx.ai" class="text-xs text-text-muted hover:text-primary transition-colors">admin@orynx.ai</a>
          <span class="text-border">|</span>
          <a href="tel:+447985309592" class="text-xs text-text-muted hover:text-primary transition-colors">07985 309592</a>
          <span class="text-border">|</span>
          <span class="text-xs text-text-muted">Edinburgh, Scotland</span>
        </div>
      </div>
    </div>
  </footer>
</template>
